### ISSUE TITLE
Definition of Open IDE

### ISSUE THREAD

**Issue by Chaser** [SASE-Space/ot-openness-comparison#1]
Does open IDE simply mean its free (including registration) requirements or that its freely extendible.

**Comment by zantiu** [comment]
open download of IDE and simulation runtime [2]
It is important that engineers have easy access to the IDE as well as runtime simulation environments. Not only for evaluation and training, but also to allow system independent tools to be able to develop and test properly with each system.

Suggest to add a separate column 'Extensible IDE'

**Comment by zantiu** [comment]
done
