### ISSUE TITLE
 Codesys 3.5 and Codesys Go!

### ISSUE THREAD

**Issue by TheColonel2688** [SASE-Space/ot-openness-comparison#10]
We should specify Codesys 3.5 (Vanilla) as in supplied directly to end users from Codesys.

The runtime supports Linux or Windows, x86 or Arm 32 bit or 64bit, along with a bunch of other Archs which you can go look up.

Offically the 3.5 IDE only supports windows.

It has been stated that Codesys Go! IDE  Will support Linux and windows and as it is web-based probably other OSes as well but that part is speculation. 

Documentation is Open https://www.helpme-codesys.com/

3.5 has a CLI which you can direct to load python Scripts to perform most IDE tasks. Scripting is free, as is the base IDE.

3.5 has an Offical Paid Testing Suit and there is a Free open Source Alternative you can find on the codesys forge as well. 

Yes the IDE extension for V3.5 cost alot of money. I think it should be free, but no one cares what I think.  

Runtime license and prices all published and explained on the website with no login necessary. If you want to buy one you don't even have to create an account (I do not think) but you do need to supply sole information like email, name, company, credit card, etc.

https://us.store.codesys.com/howto_applicationbasedlicenses

**Comment by zantiu** [comment]
Updated most of your remarks:
![image](https://github.com/SASE-Space/ot-openness-comparison/assets/11325888/c53d24b1-9488-4301-ae2c-3efc0409168d)

Linux still open. The requirement for linux is both the runtime and buildtools. Suggest to mark as not fulfilled, with a footnote mentioning the runtime can run under Linux.

**Comment by zantiu** [comment]
How about the Plain Text? How does Codesys store the code?

**Comment by zantiu** [comment]
Looks Codesys Go might have a perfect score then? Are we missing something?

**Comment by TheColonel2688** [comment]
Codesys 3.5 stores it in a binary .project file. That can be exported to XML. So it fails that column.

GO! Will be using a granular folder/file structure with the stated goal of minimizing the use of XML/JSON when ever possible ans using plain text. Basically all objects will have there own file. So it will make merging very nice.

We know nothing about scripting or extending the IDE yet. I assume neither of those will be available as first launch but will be added later. 

In theory Testinf should be available via the Open Source library CoUnit at launch but we will have to see if there are any issues with that when the time comes.

**Comment by zantiu** [comment]
Update:
![image](https://github.com/SASE-Space/ot-openness-comparison/assets/11325888/db95540b-17b1-4963-b5c7-086127727ae6)

For now assume the testing framework will be working.
