### ISSUE TITLE
Rockwell

### ISSUE THREAD

**Issue by TheColonel2688** [SASE-Space/ot-openness-comparison#11]
Rockwell gets a Big Fat red ❌️ on all of them

Technically they have a simple CLI for the IDE to do a few thinks like deploy, and import/export to XML but why even give them that, it can't do much else.

**Comment by zantiu** [comment]
How would the columns look like for Rockwell?
There's PlantPAX and FactoryTalk.
If the CLI is limited then add a ❌️with a footnote.

**Comment by TheColonel2688** [comment]
Should have specified Studio 5000 their IDE.

"Factory talk" is just marketing branding on certain products. Like their HMI FT View.

**Comment by zantiu** [comment]
Isn't PlantPax sold as full DCS? (regardless whether it is or not). So different licensing, it should have a different entry.

**Comment by TheColonel2688** [comment]
Yes it isn't free. 

P.S. what the heck is "full DCS" anyways? I always interpreted it as just communicating ans state sync between PLCs

**Comment by zantiu** [comment]
Added two entries for Rockwell. For now very red. Hope it clears up when they announce their Open Process Automation offer ...
https://www.rockwellautomation.com/en-us/company/news/press-releases/rockwell-automation-elevates-industry-leadership-through-robust-expansion-of-open-process-automation-technology-capabilities.html
