### ISSUE TITLE
Reclassification of Beckhoff TwinCAT 3, CLI Tooling [f]

### ISSUE THREAD

**Issue by benhar-dev** [SASE-Space/ot-openness-comparison#23]
Based on "CLI Tooling [f], CLI tooling or the IDE allow all compilation, build and deployment workflows to be automated" then technically  TwinCAT XAE should be a tick.  

_**"or the IDE allows compilation, build and deployment to be automated."**_  It does this by exposing the Automation Interface.  This is included when you install the free IDE TwinCAT XAE (TcXaeShell).  The IDE allows for compilation, build and deployment to be triggered using PowerShell or C# .  I understand that there is a caveat written next to it, but people quickly looking at the list may not see this and therefore incorrectly believe that IDE automation is not possible.

It's only semantics, but if this is to remain an "X" then I feel the "[f]" definition should be slightly amended.  Or an introduction of a "Yes, but..." icon. 

If in agreement, then let me know and I'll raise a pull request.

**Comment by zantiu** [comment]
I see something went wrong in an earlier PR, where it was suggested that and API/SDK on the IDE would also match this requirement. But it's not the same. The API requirement was removed again but the wording was confusing. I made a commit to clarify that at the CLI column really means CLI.  
SDK/API bringing the same functionality but without CLI can go in a footnote.

The proper way to automate is through a CLI. Controlling the IDE through an SDK/API is better than nothing, but not as good as having a proper CLI.
