### ISSUE TITLE
Explicitly mark unknown fields

### ISSUE THREAD

**Issue by shanereetz** [SASE-Space/ot-openness-comparison#3]
Suggestion:

In the table, use a default "not specified" value for each criteria. This way it's explicit if a criteria is just unknown or not yet updated, or an explicit "no."

The existing empty spaces could be used to signify "not specified", I suggest we just add a legend in that case. ie `Unmarked criteria are not necessarily a "no"`

Thoughts?

**Comment by dbrowngm** [comment]
I second this one

**Comment by zantiu** [comment]
switched to emojis
