### ISSUE TITLE
CodeSys isn't hardware indepedent

### ISSUE THREAD

**Issue by RalphKoettlitz** [SASE-Space/ot-openness-comparison#5]
CodeSys is from the perspective of a enduser not hardware independent, since PLC suppliers have to supply a special library. An example is Exor. I can't even update an older PLC without updating the firmware.

**Comment by TheColonel2688** [comment]
It is... just not for Embedded IO...

It can run on Linux or Windows on x86 or Arm...
All you need is Remote IO that is connectable from any of the supported fieldbuses.... of which there are MANY. If xodesys isn't hardware independent then nothing is.

**Comment by zantiu** [comment]
Codesys is also already running on some of the OPA testbeds, which are by definition hardware independent.

**Comment by Chaser** [comment]
Codesys can be run on x86 for as little as $29 EUR now - https://store.codesys.com/en/codesys-control-basic-s-bundle.html

**Comment by TheColonel2688** [comment]
@Chaser 

ARM too now
